config/routes.rb
Kimballtron::Application.routes.draw do
  devise_for :farmers
  resources :masteries, :only => :index
  root :to => "Welcome#index"

#TODO: This creates *member* edit and update methods as well.  why?
#rake routes:
#edit_mastery GET    /masteries/:id/edit(.:format)    {:action=>"edit", :controller=>"masteries"}
#     mastery PUT    /masteries/:id(.:format)         {:action=>"update", :controller=>"masteries"}

  resources :masteries, :only => [:edit, :update] do
    collection do
      get 'edit'
      put 'update', :as => 'update'
    end
  end

end

app/models/crop.rb
class Crop < ActiveRecord::Base
  default_scope order('market_order')
end

app/models/farm.rb
class Farm < ActiveRecord::Base
  belongs_to :farmer
  has_many :masteries
  after_initialize :set_defaults

  def set_defaults
    return unless new_record?
    self.plots ||= 0
    self.harvests_per_day ||= 0
    # count==0 is probably redundant with new_record?  paranoid.#TODO: test
    self.masteries = Mastery.one_for_each_crop if self.masteries.count == 0
  end

  private
  def self.new_farm_name
    keywords = YAML::load_file(Rails.root.join('config', 'farm_names.yml'))
    farm_types = keywords["farm_types"]
    level_names = keywords["level_names"]

    prefix = level_names[rand(level_names.size)]
    suffix = farm_types[rand(farm_types.size)]
    prefix + " " + suffix
  end
end

app/models/farmer.rb
class Farmer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_one :farm
  after_create :ensure_has_farm

  def ensure_has_farm
    # TODO: [nilfarm] this is also done in farmers_controller
    if self.farm.nil?
      self.farm = Farm.create(:name => Farm.new_farm_name)
    end
  end

end

app/models/mastery.rb
class Mastery < ActiveRecord::Base
  belongs_to :crop
  belongs_to :farm
  default_scope order('market_order')
  after_initialize :set_defaults

  validates_numericality_of :stars,
    :greater_than_or_equal_to => 0,
    :less_than_or_equal_to => 3,
    :only_integer => true
    #TODO: how come this doesn't work?
    #    :inclusion => { :in => [0, 1, 2, 3  ] }
    #    :inclusion => { :in => %w{0 1 2 3} }

  validates_numericality_of :additional_harvests,
      :greater_than_or_equal_to => 0,
      :only_integer => true

  def set_defaults
    return unless new_record?
    self.stars ||= 0
    self.additional_harvests ||= 0
    self.market_order = crop.market_order
  end

  def Mastery.one_for_each_crop
    Crop.all.collect { |crop| Mastery.new(:crop => crop) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Farmer)
      masteries_path
    else
      super
    end
  end

end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  layout nil

  # GET /crops
  # GET /crops.xml
  def index
    @crops = Crop.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @crops }
    end
  end

  # GET /crops/1
  # GET /crops/1.xml
  def show
    @crop = Crop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @crop }
    end
  end

  # GET /crops/new
  # GET /crops/new.xml
  def new
    @crop = Crop.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @crop }
    end
  end

  # GET /crops/1/edit
  def edit
    @crop = Crop.find(params[:id])
  end

  # POST /crops
  # POST /crops.xml
  def create
    @crop = Crop.new(params[:crop])

    respond_to do |format|
      if @crop.save
        format.html { redirect_to(@crop, :notice => 'Crop was successfully created.') }
        format.xml  { render :xml => @crop, :status => :created, :location => @crop }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @crop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /crops/1
  # PUT /crops/1.xml
  def update
    @crop = Crop.find(params[:id])

    respond_to do |format|
      if @crop.update_attributes(params[:crop])
        format.html { redirect_to(@crop, :notice => 'Crop was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @crop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /crops/1
  # DELETE /crops/1.xml
  def destroy
    @crop = Crop.find(params[:id])
    @crop.destroy

    respond_to do |format|
      format.html { redirect_to(crops_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_filter :authenticate_farmer!

  def show
    @farmer = Farmer.find(params[:id])
    # TODO: [nilfarm] should only have a missing farm during testing/development.
    # I don't want to auto-create a real farm here -- could mask problem
    # farms disappearing??
    if @farmer.farm.nil?
      @farmer.farm = Farm.create(:name => "** missing farm **")
    end
    @farm = @farmer.farm

  end

end

app/controllers/masteries_controller.rb
class MasteriesController < ApplicationController
  def index
    @farm = current_farmer.farm
    @masteries = current_farmer.farm.masteries
  end

  def edit
    @masteries = current_farmer.farm.masteries
  end

  def update
    if params['cancel']
      flash[:notice] = "edit cancelled; no masteries were updated."
      redirect_to masteries_path
    else
      @masteries = Mastery.update(params[:masteries].keys,
        params[:masteries].values).reject {|m| m.errors.empty?}

      if @masteries.empty?
        flash[:notice] = "masteries updated"
        redirect_to masteries_path
      else
        render :action => 'edit'
      end

    end # if cancel
  end # update
end # class

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/crops/_form.html.erb
<%= form_for(@crop) do |f| %>
  <% if @crop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crop.errors.count, "error") %> prohibited this crop from being saved:</h2>

      <ul>
      <% @crop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crops/edit.html.erb
<h1>Editing crop</h1>

<%= render 'form' %>

<%= link_to 'Show', @crop %> |
<%= link_to 'Back', crops_path %>

app/views/crops/index.html.erb
<div class="container">

	<div id="junk-header" class="span-24 last">
		<br />
		<h2>crops</h2>
	</div>

	<div id="junk-left-sidebar" class="span-2">
		<br />
	</div>

	<div id="junk-main-content" class="span-10">
		<table>
		  <tr>
		    <th>Name</th>
		    <th>Level</th>
		    <th></th>
		    <th></th>
		  </tr>

		<% @crops.each do |crop| %>
		  <tr style="background-color:<%= cycle("#f0f4fe", "#e0e4fe") -%>">
		    <td><%= crop.name %></td>
		    <td><%= crop.level %></td>
		    <td><%= link_to 'Show', crop %></td>
		    <td><%= link_to 'Edit', edit_crop_path(crop) %></td>
		  </tr>
		<% end %>
		</table>
	</div>

	<div id="junk-right-sidebar" class="span-12 last">
		<br />
	</div>	

	<div id="junk-footer" class="span-24 last">
		<br />
	</div>

</div>

app/views/crops/new.html.erb
<h1>New crop</h1>

<%= render 'form' %>

<%= link_to 'Back', crops_path %>

app/views/crops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>crop:</b>
  <%= @crop.name %>
</p>

<p>
  <b>level:</b>
  <%= @crop.level %>
</p>

<p>
  <b>hours to harvest:</b>
  <%= @crop.harvest_time %>
</p>

<div class="container">

	<div id="junk-main-content" class="span-10">
<table>
	<tr style="background-color: #e0e4fe">
		<th>mastery level</th>
    	<th>1</th>
    	<th>2</th>
    	<th>3</th>
    </tr>
	<tr style="background-color: #f0f4fe">
		<td>harvests required:</td>
		<td><%= @crop.mastery_1 %></td>
		<td><%= @crop.mastery_2 %></td>
		<td><%= @crop.mastery_3 %></td>
	</tr>
</table>
</div>

<div id="junk-right-sidebar" class="span-14 last">
	<br />
</div>

<div id="junk-footer" class="span-24 last">
	<br />
</div>

</div>

<%= link_to 'Edit', edit_crop_path(@crop) %> |
<%= link_to 'Back', crops_path %>

app/views/farmers/show.html.erb
<hr />
Welcome to your farm, affectionately known as
<h3><%= @farm.name %></h3>
<b>plots:</b> <%= @farm.plots %><br />
<b>harvests per day:</b> <%= @farm.harvests_per_day %>
<p />
<hr />

<p /><p />
	current levels:
<span style="font-family:monospace;font-weight:bold;">
	- (<%= @farm.masteries.where("stars = 0").count %>)
	* (<%= @farm.masteries.where("stars = 1").count %>)
	** (<%= @farm.masteries.where("stars = 2").count %>)
	*** (<%= @farm.masteries.where("stars = 3").count %>)
</span><br />
approximate time to complete level 1: xx days, level 2: yy months, level 3: 12 decades
<p />
	<%= link_to("edit masteries", edit_masteries_path) %>
<h3>masteries</h3>

<div id="junk-left-sidebar" class="span-2">
	<br />
</div>

<div id="junk-main-content" class="span-16">
	<table>
	  <tr>
	    <th>crop</th>
	    <th>stars</th>
	    <th>additional</th>
	    <th>hours</th>
	  </tr>

	<% @farm.masteries.each do |mastery| %>
	  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
	    <td><%= mastery.crop.name %></td>
	    <td align="right"><%= mastery.stars %></td>
		<td align="right"><%= mastery.additional_harvests %></td>
		<td align="right"><%= mastery.crop.harvest_time %></td>
	  </tr>

	<% end %>
	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kimball -- Farmville crop mastery</title>

  <%= stylesheet_link_tag "blueprint/screen", :media => "screen, projection "%>
  <%= stylesheet_link_tag "blueprint/print", :media => "print" %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag "blueprint/ie", :media => "screen, projection "%>
  <![endif]-->

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<% unless notice.blank? %>
		<p class="notice"><%= notice %></p>
	<% end %>
	<% unless alert.blank? %>
    	<p class="alert"><%= alert %></p>
	<% end %>

	<p style="font-size:175%;padding:.8em;margin-bottom:0px;border:3px solid #ddd; border-color:#90b0e5;background-color:#a1c0F6;">
		Kimball
	</p>

	<div class="container">
		<ul class="hmenu">
	  		<%= render 'devise/menu/registration_items' %>
	  		<%= render 'devise/menu/login_items' %>
		</ul>
		<%= yield %>
	</div>
</body>
</html>

app/views/masteries/edit.html.erb
<div id="junk-left-sidebar" class="span-2">
	<br />
</div>


<div id="junk-main-content" class="span-12">

<%= form_tag update_masteries_path, :method => :put do %>

<table>
  <tr>
    <th>crop</th>
    <th>stars</th>
    <th>additional</th>
    <th>L1</th>
    <th>L2</th>
    <th>L3</th>
  </tr>

  <% for mastery in @masteries %>
    <%= fields_for "masteries[]", mastery do |f| %>

  <% if mastery.errors.any? %>
  <div id="errorExplanation">
    <h2>The following errors prohibited your update from being saved:</h2>
    <ul>
    <%= mastery.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end # errors? %>

  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
	  <td><%= f.label mastery.crop.name %></td>
	  <td><%= f.text_field :stars, :size => 3 %></td>
	  <td><%= f.text_field :additional_harvests, :size => 3 %></td>
	  <td><%= mastery.crop.mastery_1 %></td>
      <td><%= mastery.crop.mastery_2 %></td>
      <td><%= mastery.crop.mastery_3 %></td>
  </tr>

  <% end # fields_for masteries %>
  <% end # masteries %>
</table>

  <p>
	<%= submit_tag "update", :name => "update"%>
	<%= submit_tag "cancel", :name => "cancel" %>
  </p>
<% end # form_tag%>

</div>

app/views/masteries/index.html.erb
<hr />
Welcome to your farm, affectionately known as
<h3><%= @farm.name %></h3>
<b>plots:</b> <%= @farm.plots %><br />
<b>harvests per day:</b> <%= @farm.harvests_per_day %>
<p />
<hr />

<p /><p />
	current levels:
<span style="font-family:monospace;font-weight:bold;">
	- (<%= @farm.masteries.where("stars = 0").count %>)
	* (<%= @farm.masteries.where("stars = 1").count %>)
	** (<%= @farm.masteries.where("stars = 2").count %>)
	*** (<%= @farm.masteries.where("stars = 3").count %>)
</span><br />
approximate time to complete level 1: xx days, level 2: yy months, level 3: 12 decades
<p />
	<%= link_to("edit masteries", edit_masteries_path) %>
<h3>masteries</h3>

<div id="junk-left-sidebar" class="span-2">
	<br />
</div>

<div id="junk-main-content" class="span-16">
	<table>
	  <tr>
	    <th>crop</th>
	    <th>stars</th>
	    <th>additional</th>
	    <th>hours</th>
	  </tr>

	<% @farm.masteries.each do |mastery| %>
	  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
	    <td><%= mastery.crop.name %></td>
	    <td align="right"><%= mastery.stars %></td>
		<td align="right"><%= mastery.additional_harvests %></td>
		<td align="right"><%= mastery.crop.harvest_time %></td>
	  </tr>

	<% end %>
	</table>

</div>

app/views/welcome/index.html.erb
<h1>Welcome to Kimball</h1>
You're finally going to have <em>fun</em> mastering your crops.<br />
<br />
<br />
<ul>
<li><b>Hank:</b> "A hound dog, eh? I used to have a hound dog...Well, not a <i>hound</i> dog. Maybe it was a <i>bird</i> dog. No...dogs don't generally fly. No, that's it! It was definitely a canary."</li>

<li><b>Oliver:</b> "You just said it was a dog!"</li>
<li><b>Hank:</b> "What was?"</li>
<li><b>Oliver:</b> "Your canary!"</li>
<li><b>Hank (looking around):</b> "Where?!"</li>
</ul>
<i>from the Wikipedia article on
	<a href="http://en.wikipedia.org/wiki/Hank_Kimball">
	Hank Kimball
</a></i>